agent: kabara.class

kabara.class:
	/usr/local/jdk1.8.0_25/bin/javac -d . -classpath . competitionJava/kabara.java

run:
	/usr/local/jdk1.8.0_25/bin/java competitionJava/kabara

calibrate:

newgame:
	rm -rf kabara.cache